# This file is machine-generated - editing it directly is not advised

[[JlrsReflect]]
path = "/home/thomas/Projects/Julia/JlrsReflect.jl"
uuid = "3e9c415f-dc9c-4763-9f27-843ce091455a"
version = "0.2.0"
